// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProto.proto

package com.kimzing.netty.protobuf.entity;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kimzing.netty.protobuf.entity.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
     * @return The header.
     */
    com.kimzing.netty.protobuf.entity.MessageProto.Header getHeader();
    /**
     * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
     */
    com.kimzing.netty.protobuf.entity.MessageProto.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.google.protobuf.Any body = 3;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <code>.google.protobuf.Any body = 3;</code>
     * @return The body.
     */
    com.google.protobuf.Any getBody();
    /**
     * <code>.google.protobuf.Any body = 3;</code>
     */
    com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
  }
  /**
   * <pre>
   * 消息定义 里面的1、2、3等数字指定了属性的位置
   * </pre>
   *
   * Protobuf type {@code com.kimzing.netty.protobuf.entity.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kimzing.netty.protobuf.entity.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              com.kimzing.netty.protobuf.entity.MessageProto.Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.kimzing.netty.protobuf.entity.MessageProto.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kimzing.netty.protobuf.entity.MessageProto.internal_static_com_kimzing_netty_protobuf_entity_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kimzing.netty.protobuf.entity.MessageProto.internal_static_com_kimzing_netty_protobuf_entity_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kimzing.netty.protobuf.entity.MessageProto.Message.class, com.kimzing.netty.protobuf.entity.MessageProto.Message.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 2;
    private com.kimzing.netty.protobuf.entity.MessageProto.Header header_;
    /**
     * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
     * @return The header.
     */
    public com.kimzing.netty.protobuf.entity.MessageProto.Header getHeader() {
      return header_ == null ? com.kimzing.netty.protobuf.entity.MessageProto.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
     */
    public com.kimzing.netty.protobuf.entity.MessageProto.HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int BODY_FIELD_NUMBER = 3;
    private com.google.protobuf.Any body_;
    /**
     * <code>.google.protobuf.Any body = 3;</code>
     * @return Whether the body field is set.
     */
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <code>.google.protobuf.Any body = 3;</code>
     * @return The body.
     */
    public com.google.protobuf.Any getBody() {
      return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
    }
    /**
     * <code>.google.protobuf.Any body = 3;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(2, getHeader());
      }
      if (body_ != null) {
        output.writeMessage(3, getBody());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHeader());
      }
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBody());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kimzing.netty.protobuf.entity.MessageProto.Message)) {
        return super.equals(obj);
      }
      com.kimzing.netty.protobuf.entity.MessageProto.Message other = (com.kimzing.netty.protobuf.entity.MessageProto.Message) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kimzing.netty.protobuf.entity.MessageProto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 消息定义 里面的1、2、3等数字指定了属性的位置
     * </pre>
     *
     * Protobuf type {@code com.kimzing.netty.protobuf.entity.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kimzing.netty.protobuf.entity.Message)
        com.kimzing.netty.protobuf.entity.MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kimzing.netty.protobuf.entity.MessageProto.internal_static_com_kimzing_netty_protobuf_entity_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kimzing.netty.protobuf.entity.MessageProto.internal_static_com_kimzing_netty_protobuf_entity_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kimzing.netty.protobuf.entity.MessageProto.Message.class, com.kimzing.netty.protobuf.entity.MessageProto.Message.Builder.class);
      }

      // Construct using com.kimzing.netty.protobuf.entity.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kimzing.netty.protobuf.entity.MessageProto.internal_static_com_kimzing_netty_protobuf_entity_Message_descriptor;
      }

      @java.lang.Override
      public com.kimzing.netty.protobuf.entity.MessageProto.Message getDefaultInstanceForType() {
        return com.kimzing.netty.protobuf.entity.MessageProto.Message.getDefaultInstance();
      }

      @java.lang.Override
      public com.kimzing.netty.protobuf.entity.MessageProto.Message build() {
        com.kimzing.netty.protobuf.entity.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kimzing.netty.protobuf.entity.MessageProto.Message buildPartial() {
        com.kimzing.netty.protobuf.entity.MessageProto.Message result = new com.kimzing.netty.protobuf.entity.MessageProto.Message(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kimzing.netty.protobuf.entity.MessageProto.Message) {
          return mergeFrom((com.kimzing.netty.protobuf.entity.MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kimzing.netty.protobuf.entity.MessageProto.Message other) {
        if (other == com.kimzing.netty.protobuf.entity.MessageProto.Message.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kimzing.netty.protobuf.entity.MessageProto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kimzing.netty.protobuf.entity.MessageProto.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.kimzing.netty.protobuf.entity.MessageProto.Header header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kimzing.netty.protobuf.entity.MessageProto.Header, com.kimzing.netty.protobuf.entity.MessageProto.Header.Builder, com.kimzing.netty.protobuf.entity.MessageProto.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
       * @return The header.
       */
      public com.kimzing.netty.protobuf.entity.MessageProto.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.kimzing.netty.protobuf.entity.MessageProto.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
       */
      public Builder setHeader(com.kimzing.netty.protobuf.entity.MessageProto.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
       */
      public Builder setHeader(
          com.kimzing.netty.protobuf.entity.MessageProto.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
       */
      public Builder mergeHeader(com.kimzing.netty.protobuf.entity.MessageProto.Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.kimzing.netty.protobuf.entity.MessageProto.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
       */
      public com.kimzing.netty.protobuf.entity.MessageProto.Header.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
       */
      public com.kimzing.netty.protobuf.entity.MessageProto.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.kimzing.netty.protobuf.entity.MessageProto.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.com.kimzing.netty.protobuf.entity.Header header = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kimzing.netty.protobuf.entity.MessageProto.Header, com.kimzing.netty.protobuf.entity.MessageProto.Header.Builder, com.kimzing.netty.protobuf.entity.MessageProto.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kimzing.netty.protobuf.entity.MessageProto.Header, com.kimzing.netty.protobuf.entity.MessageProto.Header.Builder, com.kimzing.netty.protobuf.entity.MessageProto.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.Any body_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
      /**
       * <code>.google.protobuf.Any body = 3;</code>
       * @return Whether the body field is set.
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>.google.protobuf.Any body = 3;</code>
       * @return The body.
       */
      public com.google.protobuf.Any getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public Builder setBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public Builder setBody(
          com.google.protobuf.Any.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public Builder mergeBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              com.google.protobuf.Any.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public com.google.protobuf.Any.Builder getBodyBuilder() {
        
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>.google.protobuf.Any body = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.kimzing.netty.protobuf.entity.Message)
    }

    // @@protoc_insertion_point(class_scope:com.kimzing.netty.protobuf.entity.Message)
    private static final com.kimzing.netty.protobuf.entity.MessageProto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kimzing.netty.protobuf.entity.MessageProto.Message();
    }

    public static com.kimzing.netty.protobuf.entity.MessageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kimzing.netty.protobuf.entity.MessageProto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kimzing.netty.protobuf.entity.Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 version = 1;</code>
     * @return The version.
     */
    long getVersion();

    /**
     * <code>bytes language = 2;</code>
     * @return The language.
     */
    com.google.protobuf.ByteString getLanguage();

    /**
     * <code>bytes serializer = 3;</code>
     * @return The serializer.
     */
    com.google.protobuf.ByteString getSerializer();

    /**
     * <code>bytes reqType = 4;</code>
     * @return The reqType.
     */
    com.google.protobuf.ByteString getReqType();
  }
  /**
   * Protobuf type {@code com.kimzing.netty.protobuf.entity.Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kimzing.netty.protobuf.entity.Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      language_ = com.google.protobuf.ByteString.EMPTY;
      serializer_ = com.google.protobuf.ByteString.EMPTY;
      reqType_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Header();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readInt64();
              break;
            }
            case 18: {

              language_ = input.readBytes();
              break;
            }
            case 26: {

              serializer_ = input.readBytes();
              break;
            }
            case 34: {

              reqType_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kimzing.netty.protobuf.entity.MessageProto.internal_static_com_kimzing_netty_protobuf_entity_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kimzing.netty.protobuf.entity.MessageProto.internal_static_com_kimzing_netty_protobuf_entity_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kimzing.netty.protobuf.entity.MessageProto.Header.class, com.kimzing.netty.protobuf.entity.MessageProto.Header.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    /**
     * <code>int64 version = 1;</code>
     * @return The version.
     */
    public long getVersion() {
      return version_;
    }

    public static final int LANGUAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString language_;
    /**
     * <code>bytes language = 2;</code>
     * @return The language.
     */
    public com.google.protobuf.ByteString getLanguage() {
      return language_;
    }

    public static final int SERIALIZER_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString serializer_;
    /**
     * <code>bytes serializer = 3;</code>
     * @return The serializer.
     */
    public com.google.protobuf.ByteString getSerializer() {
      return serializer_;
    }

    public static final int REQTYPE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString reqType_;
    /**
     * <code>bytes reqType = 4;</code>
     * @return The reqType.
     */
    public com.google.protobuf.ByteString getReqType() {
      return reqType_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0L) {
        output.writeInt64(1, version_);
      }
      if (!language_.isEmpty()) {
        output.writeBytes(2, language_);
      }
      if (!serializer_.isEmpty()) {
        output.writeBytes(3, serializer_);
      }
      if (!reqType_.isEmpty()) {
        output.writeBytes(4, reqType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, version_);
      }
      if (!language_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, language_);
      }
      if (!serializer_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, serializer_);
      }
      if (!reqType_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, reqType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kimzing.netty.protobuf.entity.MessageProto.Header)) {
        return super.equals(obj);
      }
      com.kimzing.netty.protobuf.entity.MessageProto.Header other = (com.kimzing.netty.protobuf.entity.MessageProto.Header) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (!getLanguage()
          .equals(other.getLanguage())) return false;
      if (!getSerializer()
          .equals(other.getSerializer())) return false;
      if (!getReqType()
          .equals(other.getReqType())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVersion());
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      hash = (37 * hash) + SERIALIZER_FIELD_NUMBER;
      hash = (53 * hash) + getSerializer().hashCode();
      hash = (37 * hash) + REQTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getReqType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kimzing.netty.protobuf.entity.MessageProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kimzing.netty.protobuf.entity.MessageProto.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kimzing.netty.protobuf.entity.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kimzing.netty.protobuf.entity.Header)
        com.kimzing.netty.protobuf.entity.MessageProto.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kimzing.netty.protobuf.entity.MessageProto.internal_static_com_kimzing_netty_protobuf_entity_Header_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kimzing.netty.protobuf.entity.MessageProto.internal_static_com_kimzing_netty_protobuf_entity_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kimzing.netty.protobuf.entity.MessageProto.Header.class, com.kimzing.netty.protobuf.entity.MessageProto.Header.Builder.class);
      }

      // Construct using com.kimzing.netty.protobuf.entity.MessageProto.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0L;

        language_ = com.google.protobuf.ByteString.EMPTY;

        serializer_ = com.google.protobuf.ByteString.EMPTY;

        reqType_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kimzing.netty.protobuf.entity.MessageProto.internal_static_com_kimzing_netty_protobuf_entity_Header_descriptor;
      }

      @java.lang.Override
      public com.kimzing.netty.protobuf.entity.MessageProto.Header getDefaultInstanceForType() {
        return com.kimzing.netty.protobuf.entity.MessageProto.Header.getDefaultInstance();
      }

      @java.lang.Override
      public com.kimzing.netty.protobuf.entity.MessageProto.Header build() {
        com.kimzing.netty.protobuf.entity.MessageProto.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kimzing.netty.protobuf.entity.MessageProto.Header buildPartial() {
        com.kimzing.netty.protobuf.entity.MessageProto.Header result = new com.kimzing.netty.protobuf.entity.MessageProto.Header(this);
        result.version_ = version_;
        result.language_ = language_;
        result.serializer_ = serializer_;
        result.reqType_ = reqType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kimzing.netty.protobuf.entity.MessageProto.Header) {
          return mergeFrom((com.kimzing.netty.protobuf.entity.MessageProto.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kimzing.netty.protobuf.entity.MessageProto.Header other) {
        if (other == com.kimzing.netty.protobuf.entity.MessageProto.Header.getDefaultInstance()) return this;
        if (other.getVersion() != 0L) {
          setVersion(other.getVersion());
        }
        if (other.getLanguage() != com.google.protobuf.ByteString.EMPTY) {
          setLanguage(other.getLanguage());
        }
        if (other.getSerializer() != com.google.protobuf.ByteString.EMPTY) {
          setSerializer(other.getSerializer());
        }
        if (other.getReqType() != com.google.protobuf.ByteString.EMPTY) {
          setReqType(other.getReqType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kimzing.netty.protobuf.entity.MessageProto.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kimzing.netty.protobuf.entity.MessageProto.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long version_ ;
      /**
       * <code>int64 version = 1;</code>
       * @return The version.
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <code>int64 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(long value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString language_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes language = 2;</code>
       * @return The language.
       */
      public com.google.protobuf.ByteString getLanguage() {
        return language_;
      }
      /**
       * <code>bytes language = 2;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes language = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString serializer_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes serializer = 3;</code>
       * @return The serializer.
       */
      public com.google.protobuf.ByteString getSerializer() {
        return serializer_;
      }
      /**
       * <code>bytes serializer = 3;</code>
       * @param value The serializer to set.
       * @return This builder for chaining.
       */
      public Builder setSerializer(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serializer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes serializer = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerializer() {
        
        serializer_ = getDefaultInstance().getSerializer();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString reqType_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes reqType = 4;</code>
       * @return The reqType.
       */
      public com.google.protobuf.ByteString getReqType() {
        return reqType_;
      }
      /**
       * <code>bytes reqType = 4;</code>
       * @param value The reqType to set.
       * @return This builder for chaining.
       */
      public Builder setReqType(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes reqType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqType() {
        
        reqType_ = getDefaultInstance().getReqType();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.kimzing.netty.protobuf.entity.Header)
    }

    // @@protoc_insertion_point(class_scope:com.kimzing.netty.protobuf.entity.Header)
    private static final com.kimzing.netty.protobuf.entity.MessageProto.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kimzing.netty.protobuf.entity.MessageProto.Header();
    }

    public static com.kimzing.netty.protobuf.entity.MessageProto.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      @java.lang.Override
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kimzing.netty.protobuf.entity.MessageProto.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kimzing_netty_protobuf_entity_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kimzing_netty_protobuf_entity_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kimzing_netty_protobuf_entity_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kimzing_netty_protobuf_entity_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MessageProto.proto\022!com.kimzing.netty." +
      "protobuf.entity\032\031google/protobuf/any.pro" +
      "to\"h\n\007Message\0229\n\006header\030\002 \001(\0132).com.kimz" +
      "ing.netty.protobuf.entity.Header\022\"\n\004body" +
      "\030\003 \001(\0132\024.google.protobuf.Any\"P\n\006Header\022\017" +
      "\n\007version\030\001 \001(\003\022\020\n\010language\030\002 \001(\014\022\022\n\nser" +
      "ializer\030\003 \001(\014\022\017\n\007reqType\030\004 \001(\014B\016B\014Messag" +
      "eProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_kimzing_netty_protobuf_entity_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kimzing_netty_protobuf_entity_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kimzing_netty_protobuf_entity_Message_descriptor,
        new java.lang.String[] { "Header", "Body", });
    internal_static_com_kimzing_netty_protobuf_entity_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kimzing_netty_protobuf_entity_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kimzing_netty_protobuf_entity_Header_descriptor,
        new java.lang.String[] { "Version", "Language", "Serializer", "ReqType", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
